name: Upload-NWN-Assets

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: docker://nwndotnet/nss2csharp:latest
    steps:
      - uses: actions/checkout@v2
      - name: pull latest nwscript.nss
        run: |
          wget https://raw.githubusercontent.com/urothis/nwn-assets/main/key-file/pkg5.bif/nwscript.nss
          dotnet /app/Nss2CSharp.dll ./ ${GITHUB_WORKSPACE}/src/test/
          cat ${GITHUB_WORKSPACE}/src/test/NWScript.cs
